### ISSUE TITLE
[BUG]: YT ReVanced modules Not Working Start from RC-1

### ISSUE THREAD

**Issue by Stillhard** [PerformanC/ReZygisk#102]
### Version

v1.0.0-rc.1

### Modules

- magisk_proc_monitor by [HuskyDG](https://github.com/Magisk-Modules-Alt-Repo/magisk_proc_monitor/)
- YT Revanced dynmount

### Description

Starting from RC-1, YT Revanced modules are not working correctly
Last known tworking with v1.0.0-270-37c40f4

### Steps to reproduce

Install magisk_proc_monitor, install yt apk from mirror, install yt revanced module that support dynmount injection

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JingMatrix** [comment]
A build with your mentioned commit reverted is here: https://github.com/JingMatrix/ReZygisk/pull/2

**Comment by ThePedroo** [comment]
I do not understand how that commit can ever break any module, though.

**Comment by ThePedroo** [comment]
That issue still happens for other users, and the fix is not proper, we must keep it open.

**Comment by ThePedroo** [comment]
Please do join our Discord, I'm conducting some tests to try to debug the issue.

**Comment by ThePedroo** [comment]
Fixed in https://github.com/PerformanC/ReZygisk/commit/399be08a196402208a10af41e48957ab10637bfb.
