### ISSUE TITLE
[BUG]: not work in magisk alpha

### ISSUE THREAD

**Issue by ammlr** [PerformanC/ReZygisk#12]
### Version

ReZygisk-v1.0.0-209-4aa8b2f

### Description

i flash via magisk alpha, not work

### Steps to reproduce

disable zygisk magisk alpha, flash rezygisk, reboot 
![Screenshot_2024-06-25-09-42-48-225_c ss vtfab wct qiq](https://github.com/PerformanC/ReZygisk/assets/30746607/251bd684-22fb-4d2a-a61c-c3a5788dc376)

### Confirmations

- [X] My environment meets the minimum requirements.
- [ ] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
What Magisk Alpha version? Can you also show the output of `magisk -v` command?

**Comment by ThePedroo** [comment]
I think I can already imagine why that happens, but I'll take a further look. Thanks for the report.

**Comment by ThePedroo** [comment]
I installed Magisk Alpha on a Tablet I had here (Tab E 2015) but I had some issues with its 32 bit nature, so it will take a bit more

However the daemon seems to be running after patching that 32 specific issue, so I am confused on why your daemon isn't working.

I'm not running the latest one as it is broken with patching 32 bit boot.imgs, so maybe that's the difference. Do you mind using ecc74d45 Magisk Alpha (27002) ?

**Comment by ThePedroo** [comment]
Oh, then I'll try to root an Android Emulator with it.

**Comment by ThePedroo** [comment]
From what I heard from @RainyXeon, it works in his device which is Magisk Alpha rooted -- And it uses the same version I used for my tablet.

**Comment by ThePedroo** [comment]
If you insist in using that version, please, send the logcat when the device is booting.

**Comment by Rtizer-9** [comment]
Even though zygisk based modules say that they're not working because zygisk isn't installed they still keep working. I'm using alpha too and all the zygisk based modules even lsposed works after installing rezygisk.

**Comment by ThePedroo** [comment]
Awesome to know, I guess we can close this.

**Comment by chaoscreater** [comment]
For anyone with the same issue, I had Magisk v30.6 and Rezygisk installed. I then uninstalled Magisk and installed Magisk Alpha and got the same error. The thing is, my Rezygisk is still enabled and so the error shouldn't have popped up. All I did was disable Rezygisk, restarted, re-enabled Rezygisk and restarted again and the error went away.
