### ISSUE TITLE
[BUG]: Invalid Root Implementation On KernelSU 0.9.4

### ISSUE THREAD

**Issue by JuanArton** [PerformanC/ReZygisk#15]
### Version

v1.0.0 (240.2bc6c0b-debug) 

### Description

Zygisk not working, it says Invalid root implementation. Where is the log file location to report?
![photo_2024-06-28_23-06-22](https://github.com/PerformanC/ReZygisk/assets/69680526/557806fd-390c-458b-9067-b5f54012d438)
![photo_2024-06-28_23-07-29](https://github.com/PerformanC/ReZygisk/assets/69680526/684a7fc7-b6c8-4032-b455-96208239a50d)

### Steps to reproduce

Flash it via KernelSU manager app.

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
The logs are sent to logcat, you can take a look there at really early boot. If possible, join our Discord and I'll be able to help you really closely to debug it.

I'm quite confused as I'm using KSU v1, which didn't change anything in modules, and it works. 🤔 In any case, join the Discord and we'll solve that out.

**Comment by tuyie78** [comment]
same as apatch also on start was ok after couple minutes it said like that

**Comment by ThePedroo** [comment]
Are you sure there wasn't any restart on the daemon? Those are only updated when the daemon is up

**Comment by tuyie78** [comment]
nothing happen

**Comment by tuyie78** [comment]
![Screenshot_20240629-022725](https://github.com/PerformanC/ReZygisk/assets/133329750/fda44310-d965-4cef-be71-7a1570702cab)

**Comment by ThePedroo** [comment]
That is not ReZygisk's official WebUI but sure.. I'll take a look soon.

**Comment by ThePedroo** [comment]
Could everyone that's getting this issue pull a CI from main branch? Please give a feedback about that.

**Comment by tuyie78** [comment]
works now on apatch

**Comment by ThePedroo** [comment]
Awesome! I am sorry for the inconvenience. It should work properly when the `add/webui` branch is merged into `main`. :)
