### ISSUE TITLE
Shamiko wont run with rezygisk

### ISSUE THREAD

**Issue by QPLAYid** [PerformanC/ReZygisk#16]
### Steps to reproduce/复现步骤

Shamiko not run on rezygisk

### Expected behaviour/预期行为

Shamiko not run on rezygisk

### Actual behaviour/实际行为

Shamiko not run on rezygisk

### KernelSU Module List/KernelSU 模块列表

```Shell
Shamiko
```

### ReZygisk version/ReZygisk 版本

1.0.0

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

1.0.0

### Version requirement/版本要求

- [X] I am using latest debug CI version of ReZygisk and enable verbose log/我正在使用最新 CI 调试版本 ReZygisk 且启用详细日志

### Logs/日志

Shamiko not run on rezygisk

**Comment by RainyXeon** [comment]
#5
