### ISSUE TITLE
[BUG]: Completely Kills Lsposed under Apatch

### ISSUE THREAD

**Issue by adrianmmiller** [PerformanC/ReZygisk#22]
### Version

Latest

### Modules

Lsposed

### Description

Disable Lsposed on boot

### Steps to reproduce

Install ReZygisk, or re-enable Lsposed and reboot

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
APatch version, ReZygisk commit being used and LSPosed version, please.

**Comment by CaptainThrowback** [comment]
Can't confirm this. Been using ReZygisk with LSPosed without any problem.

**Comment by ThePedroo** [comment]
It happens, no problem! 🤣

Thanks for using ReZygisk. :^)
