### ISSUE TITLE
zygiskd crashes when multiple root implementations are installed

### ISSUE THREAD

**Issue by CaptainThrowback** [PerformanC/ReZygisk#24]
### Version

v1.0.0-225-22e09d4-debug

### Modules

LSPosed_mod by pumPCin version 1.9.3 (7527)
zygisk-detach by j-hc version 1.18.0

### Description

My boot is patched for both KernelSU (LKM) and APatch. I'm only using KernelSU for root, however, with the su path in APatch set to the KernelSU daemon. Zygisk Next correctly identifies either "Multiple" root implementations (if I leave the APatch su path as stock /system/bin/su), or as only KernelSU with the setup I initially mentioned.

ReZygisk, however, shows this in the log and on the module page:
`I/zygiskd64( 1456): zygiskd: current root impl: None`

### Steps to reproduce

Install multiple root implementations.
Watch zygiskd crash.

### Logs

[liveboot.log](https://github.com/user-attachments/files/16164727/liveboot.log)
![Screenshot_20240710-114633_KernelSU](https://github.com/PerformanC/ReZygisk/assets/1119956/b626f6b3-9c65-481c-9e73-e4f83ffb731a)

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnadgnaoh** [comment]
LSPosed_mod by pumPCin makes ReZygisk crashed
Try with this: https://github.com/mywalkb/LSPosed_mod/actions/runs/9687297318

**Comment by CaptainThrowback** [comment]
> LSPosed_mod by pumPCin makes ReZygisk crashed
> Try with this: https://github.com/mywalkb/LSPosed_mod/actions/runs/9687297318

No, it doesn't. I've been using it all along with APatch without any issue. It wasn't until I combined it with KernelSU that zygiskd began crashing. But just for your satisfaction:
![Screenshot_20240711-111036.png](https://github.com/PerformanC/ReZygisk/assets/1119956/2f770439-91cb-404c-bae1-9f41826630dd)

**Comment by ThePedroo** [comment]
Fixed in https://github.com/PerformanC/ReZygisk/commit/7586c46ce482b774ae8794d0a23759906e4d24d9
