### ISSUE TITLE
Someone who maintained the zygisk next project before you suggested merging their code to reduce the workload

### ISSUE THREAD

**Issue by Nimpip** [PerformanC/ReZygisk#31]
### Description

https://github.com/Admirepowered/Zygisk_mod

### Reason

Someone who maintained the zygisk next project before you suggested merging their code to reduce the workload

### Confirmations

- [X] This feature is not already implemented.
- [X] I have verified that this is not a duplicate feature request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CaptainThrowback** [comment]
Is there some code there that hasn't already been merged? Pretty sure the relevant code from there has already been used.

**Comment by ThePedroo** [comment]
The important commits were merged AFAIK, now we're currently maintaining on our own 🤔

**Comment by Nimpip** [comment]
It does look that way. Great
