### ISSUE TITLE
Enabling rezygisk in kernelsu breaks samsung's internet browser

### ISSUE THREAD

**Issue by Https-not** [PerformanC/ReZygisk#34]
### Version

1.0.0-279

### Modules

None

### Description

After enabling the rezygisk module, samsung internet browser starts to freeze and stops opening sites (an empty black window is displayed instead of the site content). Clearing the application data does not solve the problem. The above problems disappear after the module is turned off

### Steps to reproduce

1.Download and enable rezygisk module in kernelsu app (the work of magisk and apatch has not been checked)
2. Download(or launch, if you device is samsung and you are use SIB) Samsung Internet Browser 
3. Apply reboot
4. Try launch SIB and check his work

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
I don't see why this would have any connection as if it was ReZygisk, all other apps would also crash.
