### ISSUE TITLE
Automatically switch the dark mode

### ISSUE THREAD

**Issue by Keeperorowner** [PerformanC/ReZygisk#35]
### Description

It is hoped that the webUI can automatically switch the dark mode along with the system, instead of manually switching

### Reason

automatically switch the dark mode

### Confirmations

- [X] This feature is not already implemented.
- [X] I have verified that this is not a duplicate feature request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RainyXeon** [comment]
Now avaliable on 8e4bc1c495d1f7debf69fff7a1f65a040042caf9

**Comment by RainyXeon** [comment]
> There will be an error in the bottom column color when selecting Follow system![Screenshot_2024-07-25-11-20-06-71_26ccd656f4ada08d09da6514b90ed2c0.jpg](https://private-user-images.githubusercontent.com/172187161/351945422-977c08af-1495-4739-a3f0-c1233d92a59b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Nzg1OTAsIm5iZiI6MTcyMTg3ODI5MCwicGF0aCI6Ii8xNzIxODcxNjEvMzUxOTQ1NDIyLTk3N2MwOGFmLTE0OTUtNDczOS1hM2YwLWMxMjMzZDkyYTU5Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwMzMxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODRlNzBlMWM4MjgyMGUxYmNjZjEzYjVhYzUwNDA3YWU2NDJiZTc2ZDI3ZjY3NTE2ODZiNDZiOWZmYmQzOTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bsXVxcmUBfNWN09AaoiwQbzbzlXkkgiopzW_i2brKec)
> 
> ![Screenshot_2024-07-25-11-20-13-71_26ccd656f4ada08d09da6514b90ed2c0.jpg](https://private-user-images.githubusercontent.com/172187161/351945437-d19b3a94-21a3-40cb-92aa-953a8203ba66.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Nzg1OTAsIm5iZiI6MTcyMTg3ODI5MCwicGF0aCI6Ii8xNzIxODcxNjEvMzUxOTQ1NDM3LWQxOWIzYTk0LTIxYTMtNDBjYi05MmFhLTk1M2E4MjAzYmE2Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwMzMxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzVmM2NhZTUyM2JkZDFmNDhhM2VmOWUxZThhMDYxZGY4NDYzN2E2MjhkZDU4MDgzN2ZmYmZlYzhmZThkNTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tk2g-VaKCOAmgWGmA3f5FydgHT2m8gdeN6-KhoVVgK8)

I can't confirm this since it still working on my device. Cau you go to error history and send the log if exist?

**Comment by ThePedroo** [comment]
Can confirm happens on my device too.

**Comment by RainyXeon** [comment]
🤔
I will check later. Maybe something mess up with js/theme/light.js ig so

**Comment by RainyXeon** [comment]
@ThePedroo @Keeperorowner 
Can I get the way to reproduce?

**Comment by RainyXeon** [comment]
@Keeperorowner @ThePedroo can u check e8e1b72e16b703d181eabc1d4b61ff7c4bc9a2cd?

**Comment by tuyie78** [comment]
works now with system detect theme
