### ISSUE TITLE
WebUI not working on 64 bit only devices

### ISSUE THREAD

**Issue by miuirussia** [PerformanC/ReZygisk#36]
### Version

v1.0.0 (319-2e82988-release)

### Modules

my translation module with zygisk module version 1.0.0

### Description

Error when I open WebUI
![Screenshot_2024-07-23-21-34-44-388_me bmax apatch](https://github.com/user-attachments/assets/e59ccfe1-545a-4132-ba10-c89112b931bc)

### Steps to reproduce

Open WebUI

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Known issue, usually with devices that do not support 32 bit or 64 bit.

**Comment by ThePedroo** [comment]
Fixed in 30f879cd5f4082b8f220d4db8bec4b34fc643fc1.

**Comment by miuirussia** [comment]
Updated to 334-b4305da, but problem not fixed

**Comment by miuirussia** [comment]
@ThePedroo

**Comment by miuirussia** [comment]
Created real fix of this ticket
