### ISSUE TITLE
[BUG]:  Magisk shows as no Zygisk and modules show as Zygisk not enabled after flashing and rebooting

### ISSUE THREAD

**Issue by kartikbillimoria** [PerformanC/ReZygisk#45]
### Version

ReZygisk-v1.0.0-344-b77aa98-release

### Modules

Play Integrity Fork v9
Tricky Store v1.0.3
Zygisk - LSPosed v1.10.0
Zygisk Assistant v2.1.2
Zygisk-Detach v1.18.0

### Description

Modules dependent on Zygisk still work fine but show as Module suspended because Zygisk is not enabled. On Magisk home page, Zygisk shows as no.

Using ZygiskNext doesn't have this behaviour.

Using canary version of Magisk v27006

### Steps to reproduce

Flash as normal, reboot while having built-in Zygisk disabled in Magisk.

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
I'll take a look because maybe there's an environment variable that marks as Zygisk enabled. But just to put in highlight: This is harmless

**Comment by kartikbillimoria** [comment]
Adding some photos for reference
![Screenshot_20240807-084116](https://github.com/user-attachments/assets/b3a72190-bec4-4a4d-9794-f791ef1bf4b5)
![Screenshot_20240807-084122](https://github.com/user-attachments/assets/33ff7ab8-27d2-44e8-ad32-eef8bbb58c5c)
![Screenshot_20240807-084130](https://github.com/user-attachments/assets/faae7472-227d-4141-9cf3-ae76dc8c35d2)

**Comment by tuyie78** [comment]
![Screenshot_20240807-013932](https://github.com/user-attachments/assets/568269e0-e903-4bac-bea6-bd72f9d1ac14)
mine also but not use rezygisk but zygisk next

**Comment by tuyie78** [comment]
maybe different issue

**Comment by kartikbillimoria** [comment]
With ZygiskNext, everything is as it should be, it does get recognized by Magisk as well as all the modules, see screenshots:
![Screenshot_20240807-085224](https://github.com/user-attachments/assets/cbad3a4a-f0fc-48ef-b07a-b7fbf7c15c8c)
![Screenshot_20240807-085238](https://github.com/user-attachments/assets/fd7deadf-99d1-428a-ad30-a5990d62ed08)
![Screenshot_20240807-085246](https://github.com/user-attachments/assets/d312eaae-87b2-4ed2-abe7-8f0dc7e2ef13)

**Comment by ThePedroo** [comment]
https://github.com/topjohnwu/Magisk/blob/master/app%2Fcore%2Fsrc%2Fmain%2Fjava%2Fcom%2Ftopjohnwu%2Fmagisk%2Fcore%2FInfo.kt#L44

We just need to set an env var -- I'll be commiting that to main soon.

**Comment by ThePedroo** [comment]
Please try ` fix/magisk-zygisk-modules-as-enabled`. If it works, I'll make the code more robust and commit to main.

**Comment by kartikbillimoria** [comment]
Thanks, I'll give it a go and report shortly.

**Comment by ThePedroo** [comment]
> Thanks, I'll give it a go and report shortly, how do I download the new file to flash?

In the CIs: https://github.com/PerformanC/ReZygisk/actions/runs/10287112095?pr=46

(Forgot I needed to open a PR to run the CI)

**Comment by kartikbillimoria** [comment]
I tested this new build and it's still the same issue, zygisk not detected yet it's running.

**Comment by kartikbillimoria** [comment]
Any other update that you want me to try?

**Comment by ThePedroo** [comment]
Soon, hopefully

**Comment by ThePedroo** [comment]
Please try https://github.com/PerformanC/ReZygisk/commit/763e94b9b6067ebde5063451c6c7ac27df540a04

**Comment by ThePedroo** [comment]
Please upload the logcat

**Comment by ThePedroo** [comment]
Perhaps for Kitsune is: https://xdaforums.com/t/discussion-kitsune-mask-another-unofficial-mask-of-magisk.4460555/post-89650752 ?

As people told even with Zygisk Next is shows as disabled?

**Comment by kartikbillimoria** [comment]
Tested ReZygisk on Magisk Canary with the latest CI Build from Actions and it's working. It shows as Zygisk is available and all modules are enabled.

I haven't tested it on Kitsune yet.

I will test it and report.

Thanks for all the efforts and getting this working with official Magisk.

**Comment by kartikbillimoria** [comment]
Update: Zygisk Detach module doesn't work when trying to run it on termux with su privileges.

**Comment by ThePedroo** [comment]
The fixes doesn't affect Zygisk-detach, so it is unrelated

**Comment by kartikbillimoria** [comment]
It does work with build in Zygisk as well as ZygiskNext

**Comment by RainyXeon** [comment]
> It does work with build in Zygisk as well as ZygiskNext

Please report a new issue bc this issue I think is not related to the current one.
