### ISSUE TITLE
[BUG]: Zygisk-Detach doesn't work when using ReZygisk

### ISSUE THREAD

**Issue by kartikbillimoria** [PerformanC/ReZygisk#48]
### Version

ReZygisk-v1.0.0-234-f1ba34f-release

### Modules

Play Integrity Fork v9
Tricky Store v1.0.3
Zygisk - LSPosed v1.10.0
Zygisk Assistant v2.1.2
Zygisk-Detach v1.18.0

### Description

I have two phones, one with Magisk Canary 27006 and the other with Kitsune Canary. Whilst the issue of ReZygisk not being picked up by either Magisk or Kitsune has been resolved there seems to be another issue.

Phone 1: Magisk Canary 27006 with ReZygisk
Zygisk Detach doesn't work when trying to use it via Termux whereas it works when using ZygiskNext.

Phone 2: Kitsune Canary with ReZygisk
Zygisk Detach doesn't work when trying to use it via Termux, it is the same behaviour with ZygiskNext. I'm guessing it's the way Kitsune is hence might be causing issues.

### Steps to reproduce

Disable Built-In Zygisk
Flash ReZygisk
Flash Zygisk-Detach
Reboot
Open Termux
su -c detach

It doesn't work.

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bugreportion** [comment]
Use [zygisk-detach-app](https://github.com/j-hc/zygisk-detach-app).

**Comment by LeCmnGend** [comment]
Same here on ksu 11928

**Comment by ThePedroo** [comment]
Please share logcat.

**Comment by LeCmnGend** [comment]
Try action 301. Detach works normal for me

**Comment by LeCmnGend** [comment]
![Screenshot_20241218-231944_KernelSU](https://github.com/user-attachments/assets/4e7f0848-7bbc-4b53-b84a-a6237d23b0bd)
![Screenshot_20241218-231921_zygisk-detach](https://github.com/user-attachments/assets/91e032e9-145b-450e-bc00-2673d7c5d29d)

**Comment by ThePedroo** [comment]
Please confirm if it works on even newer builds.

**Comment by ThePedroo** [comment]
I`ll take as a yes. Please re-open if not.
