### ISSUE TITLE
[BUG]: False Detect

### ISSUE THREAD

**Issue by ammlr** [PerformanC/ReZygisk#49]
### Version

ReZygisk-v1.0.0-355-e72219e-release

### Modules

only apatch and lsposed

### Description

the module is active, but the status in not active
![Screenshot_2024-08-18-09-37-37-750_me bmax apatch](https://github.com/user-attachments/assets/b0e4256c-c38d-43fd-a242-d54e0fc48549)
![Screenshot_2024-08-18-09-37-35-186_me bmax apatch](https://github.com/user-attachments/assets/627ea2b4-ece0-443d-be3e-9be8edc769dc)

### Steps to reproduce

open apatch, open modules, web ui

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Web UI is still in development, and ptrace is going through changes
