### ISSUE TITLE
[BUG]: Shamiko not work

### ISSUE THREAD

**Issue by ammlr** [PerformanC/ReZygisk#5]
### Version

ReZygisk-v1.0.0-205

### Description

great work. I use magisk alpha, when installing rezygisk Shamiko it doesn't work. "unsupported environment"

please fix

### Steps to reproduce

flash, install, reboot, shamiko not work

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
It is known that Shamiko doesn't work with ReZygisk, however, due to the nature of Shamiko being closed source, this makes near impossible to make it compatible as we don't know what it is missing. I believe the same happens with the last FOSS release of Zygisk Next, as we didn't introduce (major) regressions into the code base, but I'll be looking into it.

**Comment by ThePedroo** [comment]
Sadly the first statement is true, but it is also true for Shamiko as well. I didn't find any app yet where Zygisk Assistant fails, but for the time being, you either can use 1.0.6 Zygisk Next + Shamiko, ReZygisk + Zygisk Assistant (if you're using LSPosed, it also is often detected)

**Comment by ThePedroo** [comment]
Shamiko seems to be verifying the signature hash of the Zygisk module, I don't think we can bypass that without being forced to reverse-engineer it.

Using builds from Zygisk Next, the last FOSS release, v4-0.9.1.1, works, but when building it locally, it displays the error message.

**Comment by RinLin-NYA** [comment]
The same issue is appeared on APatch. To this question, we aften choose not to use shamiko, just like our documents said,

>
> We can not support Shamiko due to its proprietary and no updates.
>

**Comment by ThePedroo** [comment]
Sad to hear that. However, there's a PR (Thanks Reveny for the original PR!) with maps hiding which highly improves the ability of ReZygisk to hide. With it you can inject code on Momo without it detecting, however more sophisticated apps like Native Test and Native Detector still detect it, however *most* apps will pass.

* PRs to better hiding will be accepted :)

You can still use Zygisk Assistant or 0.7.5 Shamiko (which you won't want to use as it would defeat the purpose of ReZygisk which is bringing zygisk back to FOSS) if any app fails, but I recommend to use the least amount of modules possible.

**Comment by ThePedroo** [comment]
There's nothing we can do from our side, the best try is to use better forks of LSPosed in that case. That limitation is purely intentional from their side.

**Comment by tuyie78** [comment]
mine with latest 27004 magisk alpha

**Comment by Meltartica** [comment]
If you're referring to Shamiko, then there's some that say it doesn't work on Magisk 27004 (Latest version only supports 27003). Bank apps tend to detect zygote processes (Zygisk), so let's say they use AppDome protection. Then there's no way in the meantime to fully hide Zygisk, so you'll either have to disable Zygisk first to use the bank apps or choose not to use zygisk.
