### ISSUE TITLE
[BUG]: Regression after implementing maps hiding

### ISSUE THREAD

**Issue by CoelacanthusHex** [PerformanC/ReZygisk#51]
### Version

v1.0.0-210-af96b85-release

### Modules

* Adreno Gpu Driver by LH version v1.0 (Note: All GPU driver module by LH use the same name and version) (GPU_v782_M-KSU.zip from https://t.me/lhmodshare)
* SkiaVk as Default Renderer by Kamin4ri version v1.0 (from https://t.me/adreno_konabess/37936)

### Description

There is a regression: if you flash some module to update the GPU driver (e.g. GPU_v782_M-KSU.zip from https://t.me/lhmodshare) and set HWUI renderer to skiavk via `debug.hwui.renderer=skiavk` system.prop, you will get metadata mismatched and a black screen in applications with umount modules. This problem was introduced in https://github.com/PerformanC/ReZygisk/commit/af96b85a91ba3d1107884c61484f276cc1a4caff and the issue disappeared after switching back to https://github.com/PerformanC/ReZygisk/commit/4aa8b2f8282e7d67fdedefd80250a8fa390f4b38. So it should be a regression of https://github.com/PerformanC/ReZygisk/commit/af96b85a91ba3d1107884c61484f276cc1a4caff.

_Originally posted in https://github.com/PerformanC/ReZygisk/issues/9#issuecomment-2330723296_

### Steps to reproduce

1. Install ReZygisk https://github.com/PerformanC/ReZygisk/commit/af96b85a91ba3d1107884c61484f276cc1a4caff
2. Install both 2 modules
3. Set "Umount modules" in some applications
4. Run these applications
5. You will get a black screen and see some errors in the log.
6. Switch back to https://github.com/PerformanC/ReZygisk/commit/4aa8b2f8282e7d67fdedefd80250a8fa390f4b38
7. Try 2~4 again
8. The problem disappeared.

### Logs

```
09-05 14:33:47.243  7536  8145 E AdrenoUtils: <validate_resource_memory_layout_metadata:2073>: Metadata driver version mismatch {store uuid 04000000-0100-0000-0100-000000000000, struct uuid 02000000-0000-0000-0000-000000000000}
09-05 14:33:47.243  7536  8145 E HWUI    : SkSurfaces::WrapAndroidHardwareBuffer failed
09-05 14:33:47.243  7536  8145 E HWUI    : VulkanSurface::dequeueNativeBuffer called with an invalid surface!
```

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CoelacanthusHex** [comment]
> It's not about map hiding

But it appeared after the commit introducing maps hiding, so it should be related to implementation. Maybe the implementation touched other code and led this problem?

**Comment by CoelacanthusHex** [comment]
> Unmount modules feature cause the problem

But why is there no problem using ReZygisk before this commit and ZygiskNext? If Umount modules cause problem, it should always be here.

**Comment by CoelacanthusHex** [comment]
> Because this commit added auto-unmount

Is there any way to disable auto-umount or make an updated GPU driver work well with auto-umount?

**Comment by CoelacanthusHex** [comment]
> Without auto unmount, root can be detected

Or is there any way to make an updated GPU driver work well with auto-umount?

**Comment by ThePedroo** [comment]
So it works with Zygisk Next..? Well, I am making a branch removing some of those hidings, trying to fix more detection points. I suggest you fork the repository and revert the commit added for maps hiding which also included module hiding (auto umount), if not, I would happy to provide a built zip with such change

**Comment by CoelacanthusHex** [comment]
> So it works with Zygisk Next..?

Exactly, the last open-source version of Zygisk Next. It should be the same as the fork base of ReZygisk. I mention it just to point out it's a new issue.

**Comment by CoelacanthusHex** [comment]
> Disable driver preload by `resetprop ro.zygote.disable_gl_preload 1`

Looks like the GPU driver module by LH set it in system.prop.
