### ISSUE TITLE
[BUG]: Symbol resolution for `/linker` in Android 15

### ISSUE THREAD

**Issue by JingMatrix** [PerformanC/ReZygisk#63]
### Version

v1.0.0 (234-f1ba34f-debug)

### Modules

Zygisk - LSPosed by JingMatrix v1.10.1 (7118) 

### Description

In Android 15, the symbols `__dl__ZL6solist`, `__dl__ZL6somain`  and `__dl__ZL4vdso` are no longer present, so that `SoList::Initialize()` always fails.

Indeed they are replaced by names like `__dl__ZL6solist.llvm.7690929523238822858` and so on.

I update the `readelf` output of `linker64`  binary as evidence
[linker_readelf.txt](https://github.com/user-attachments/files/17452121/linker_readelf.txt) 

### Steps to reproduce

1. Use Android 15
2. Install a debug version of LSPosed
3. See entries like `[ 2024-10-19T20:53:12.823     1000:  1586:  1586 E/zygisk-core64   ] Failed to initialize SoList`

### Logs

Here is the LSPosed log:
[verbose_2024-10-19T20:53:12.156478.log](https://github.com/user-attachments/files/17452126/verbose_2024-10-19T20.53.12.156478.log)

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
The best approach would be completely removing SO list hiding as it's just more of a workaround to a bigger problem, I'll investigate to see the next step. Thank you.

**Comment by JingMatrix** [comment]
You commit 5b5c2f have fixed the issue. Here is the logs for your information:
[verbose_2024-11-23T20:18:52.740303.log](https://github.com/user-attachments/files/17882305/verbose_2024-11-23T20.18.52.740303.log).

**Comment by ThePedroo** [comment]
I may add that there are Android 15 devices that seem to not have that llvm sufix, however the made PR should fix in any case.

**Comment by JingMatrix** [comment]
Solist hiding is surely needed. Current method using `nullify_path` can't still be detected, because empty pathname is simply too strange.

We should drop those libraries in the SoList
