### ISSUE TITLE
这是适配apatch最好用的版本吗[BUG]: 

### ISSUE THREAD

**Issue by rhapsodw** [PerformanC/ReZygisk#82]
### Version

1.0

### Modules

1.0

### Description

1.0

### Steps to reproduce

1.0

### Logs

1.0

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Also, please next time use English (even if it's with translator) and fill the areas of the form.
