### ISSUE TITLE
[BUG]: Injection can be detected by another application.

### ISSUE THREAD

**Issue by middle1** [PerformanC/ReZygisk#94]
### Version

v1.0.0-rc.1

### Modules

Play Integrity fix by chiteroman version 18.0

### Description

I've tried several forks of zygisk, including this one, and each has issues with hiding. This one has the same problem. It has the same detection as shamiko. The Hunter app shows something like this: inode mismatching -> /dev/zero 2363 195558. I'm not sure if this fork is specifically aimed at hiding zygisk, but the problem remains unresolved.

### Steps to reproduce

I have a simple module, and if I don't close it using the DLCLOSE_MODULE_LIBRARY flag, there is detection. Different combinations with magisk delta and the regular one.

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
It is expected to not dlclose the library when not setOptions the DLCLOSE_MODULE_LIBRARY, leaving memory detections. I'm afraid it's outside of our control to fix, please re-open if you believe the opposite.
