### ISSUE TITLE
[BUG]: zygiskd64 exited but not restart

### ISSUE THREAD

**Issue by ccaapton** [PerformanC/ReZygisk#97]
### Version

v1.0.0 (298-cefff71-release)

### Modules

Play Integrity Fork  (v12) by osm0sis
zygisk-sui (v13.5.1) by Rikka
zygisk_lsposed(v1.9.3_mod (7244)) by "LSPosed Developers"

### Description

Normally the process  "zygisk-ptrace64 monitor" have multiple child process, including "zygiskd32" and "zygiskd64". But sometimes zygiskd64 will exit and will not restart.

When this happens, all 64-bit app will stuck on the startup screen. I can solve this by manually start zygiskd64 in ssh with root.

935 ?        S      0:00 ./bin/zygisk-ptrace64 monitor
  957 ?        S      0:00  \_ ./bin/zygiskd32

### Steps to reproduce

Did not find a quick way to 100% reproduce. I wrote a bash script
```
wait $zygiskd64_pid; logcat -d > /dev/zygiskd_crash.log 
```
waited two days to get a logcat.

### Logs

12-06 20:36:00.188   950   950 I zygiskd64:  - Polling companion for module "playintegrityfix"
12-06 20:36:00.188   950   950 I zygiskd64:  - Sending companion fd socket of module "playintegrityfix"
12-06 20:36:00.188  6269  6269 I zygiskd64: New companion request.
12-06 20:36:00.188  6269  6269 I zygiskd64:  - Module name: playintegrityfix
12-06 20:36:00.188  6269  6269 I zygiskd64:  - Client fd: 5
12-06 20:36:00.193   950   950 I zygiskd64:  - Polling companion for module "zygisk-sui"
12-06 20:36:00.193   950   950 I zygiskd64:  - Sending companion fd socket of module "zygisk-sui"
12-06 20:36:00.193 31608 31608 I zygiskd64: New companion request.
12-06 20:36:00.193 31608 31608 I zygiskd64:  - Module name: zygisk-sui
12-06 20:36:00.193 31608 31608 I zygiskd64:  - Client fd: 5
12-06 20:36:00.240  8999  8999 I zygisk-core64: Cleared SOList entry for jit-cache
12-06 20:36:00.251  8999  8999 I zygisk-core64: Randomized Memory map name: umRCSTe543
12-06 20:36:18.911   950   950 I zygiskd64:  - Polling companion for module "zygisk-sui"
12-06 20:36:18.911   950   950 I zygiskd64:  - Sending companion fd socket of module "zygisk-sui"
12-06 20:36:18.911 31608 31608 I zygiskd64: New companion request.
12-06 20:36:18.911 31608 31608 I zygiskd64:  - Module name: zygisk-sui
12-06 20:36:18.911 31608 31608 I zygiskd64:  - Client fd: 5
12-06 20:36:26.757   950   950 I zygiskd64:  - Polling companion for module "zygisk-sui"
12-06 20:36:26.757   950   950 I zygiskd64:  - Sending companion fd socket of module "zygisk-sui"
12-06 20:36:26.758 31608 31608 I zygiskd64: New companion request.
12-06 20:36:26.758 31608 31608 I zygiskd64:  - Module name: zygisk-sui
12-06 20:36:26.758 31608 31608 I zygiskd64:  - Client fd: 5
12-06 20:37:27.823  2152  5299 W InputManager-JNI: Input channel object 'e6465d7 org.mozilla.fenix/org.mozilla.fenix.App (client)' was disposed wit
hout first being removed with the input manager!
12-06 20:37:27.838   947   947 D Zygote  : Forked child process 9460
12-06 20:37:27.840  2152  2200 I ActivityManager: Start proc 9460:org.mozilla.fenix:media/u0a217 for service {org.mozilla.fenix/org.mozilla.gecko.m
edia.MediaManager}
12-06 20:37:27.855  2152  2190 I ActivityManager: Killing 3642:org.mozilla.fenix:tab7/u0a217 (adj 250): remove task
12-06 20:37:27.856  2152  2190 I ActivityManager: Killing 7410:org.mozilla.fenix:tab8/u0a217 (adj 250): remove task
12-06 20:37:27.856  2152  2190 I ActivityManager: Killing 9460:org.mozilla.fenix:media/u0a217 (adj -10000): remove task
12-06 20:37:27.856  2152  2190 I ActivityManager: Killing 9118:org.mozilla.fenix:tab22/u0a217 (adj 250): remove task
12-06 20:37:27.856  2152  2190 I ActivityManager: Killing 3569:org.mozilla.fenix/u0a217 (adj 250): remove task
12-06 20:37:27.857  2152  2190 I ActivityManager: Killing 6435:org.mozilla.fenix:gpu/u0a217 (adj 250): remove task
12-06 20:37:27.857  2152  2190 I ActivityManager: Killing 8173:org.mozilla.fenix:utility/u0a217 (adj 250): remove task
12-06 20:37:27.863   947   947 I Zygote  : Process 9460 exited due to signal 9 (Killed)
12-06 20:37:26.686     0     0 E         : ibat_ua =-737000
12-06 20:37:27.746     0     0 I binder  : 9470:9470 ioctl 40046210 7fd1d5bcc4 returned -22
12-06 20:37:27.913   935   935 W zygisk-ptrace64: daemon64 pid 950 exited: 0xd signaled with PIPE(13)
12-06 20:37:27.913   935   935 E zygisk-ptrace64: malloc daemon64 error info failed

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePedroo** [comment]
Which branch is that build from, after all?

**Comment by ccaapton** [comment]
[action link](https://github.com/PerformanC/ReZygisk/actions/runs/11868380285)

**Comment by ccaapton** [comment]
@Keeperorowner Actually I started waitpid on the latest CI version last night. will post the newest log when available.
As for Lsposed, thanks for the suggestion on "Jing Matrix", but I think the problem here is two folds:

a) zygiskd64 crashed
b) zygiskd64 never restart itself.

rogue modules could cause (a) to happen, but at least (b) can be fixed regardless of what modules users run

**Comment by ThePedroo** [comment]
https://github.com/PerformanC/ReZygisk/commit/95073d9f4a61317295309f24e1843f6b9605ef66 This may fix it. Sorry for the delay.

**Comment by ThePedroo** [comment]
Marking as closed till proven the contrary. Cannot repro (anymore?)

**Comment by amogus07** [comment]
I‘m facing the same problem, both with the latest realease and the latest CI version
